Tooltips.ToggleMEStorage = {
title = 'Toggle M/E Storage', 
description = 'Switches between Mass and Energy storage Buffs. Default is Mass Storage.', } 
Tooltips.BuffAIs = { 
title = 'Buff AI Land', 
description = "Increases all Mobile non-Air AI units' Level by 1.", } 
Tooltips.BuffButtonDef = { 
title = 'Buff AI Defense', 
description = "Increases all defensive Structure and Factory AI units' Level by 1.", } 
Tooltips.BuffAIsSea = { 
title = 'Buff AI Naval', 
description = "Increases all Naval AI units' Level by 1.", } 
Tooltips.BuffAIsAir = { 
title = 'Buff AI Air', 
description = "Increases all Air AI units' Level by 1.", } 
Tooltips.ToggleVetIsOn = { 
title = 'Veteran Building Enabled', 
description = "Built units gain 20% of the level of the builder, cost more.", } 
Tooltips.ToggleVetIsOff = { 
title = 'Veteran Building is Off', 
description = "Veteran Building disabled", } 
Tooltips.ToggleVet2 = { 
title = 'Toggle Veteran Building 20%', 
description = "When enabled, all units started to be built by this builder gain ~20% of its level, costs increase by 20% each extra level.", } 
Tooltips.AutoRevive = { 
title = 'Auto Revive count', 
description = "Displays the number of Auto-revives left for this unit.", }
Tooltips.Buildrate = { 
title = 'Buildrate', 
description = "Determines the speed at which this unit can build. Higher is better.", } 
Tooltips.XpNumericals = { 
title = 'XP', 
description = "Current XP = How much this unit has collected.\n\n next Level = Amount needed to gain an additional level. \n\n worth = Amount gained by an enemy if it kills this unit.", }
Tooltips.Level = { 
title = 'Level', 
description = "A Unit gains roughly 10% of improvements per level, at Level 11 it is about twice as strong.", } 
Tooltips.BuildXPEnabled = { 
title = 'Toggle Build XP', 
description = "XP gains by building enabled/disabled. Affects all current units, not those built later.", } 
Tooltips.ShareXPEnabled = { 
title = 'Toggle XP Sharing', 
description = "On killing a unit, half the XP gained is shared with allied units around the dead unit.", } 
Tooltips.AIVetBuildEnabled = { 
title = 'Toggle AI Building Veterans', 
description = "Toggles all AI building Veterans. Also affects units built later.", } 
Tooltips.bBBase = { 
title = 'Buff AI Base', 
description = "Increases all Structure units' Level by 1.", } 
Tooltips.ToggleBalance = { 
title = 'Toggle SP/MP Balance', 
description = "Affects over time XP gains, Teleport time reductions, Shield behaviour.", } 
Tooltips.Jump = { 
title = 'Jump', 
description = [[Select a Target to jump to after pressing this button. modifiers: (clicking this button) Right Mouse Button: Formation Jump Middle Mouse Button: Long-range Jump(~2-14x cost) Shift: a shallow Jump(.5x) Alt: Dance of Death (each 1K target hp cost 300 mass) Ctrl: Bulletstorm(7x) ]], } 
Tooltips.Jump2 = { 
title = 'Jump', 
description = [[Select a Target to jump to after pressing this button. modifiers: (clicking this button) Right Mouse Button: Formation Jump Middle Mouse Button: Long-range Jump(~2-14 cost) Shift: a shallow Jump(.5x) Ctrl: BulletStorm (7x) Alt: Dance of Death (each 1K target hp cost 300 mass) Details: Range octagons are estimated and do
 not take target elevation into account. Jumping from/to high positions requires you to be closer. Please read jump costs included with this mod
for detailed costs breakdowns. AreaDamage is affected by jump length and height. Orders can not be queued before jumping. ]], }